<?php

namespace ContainerPYTR9HB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CN6aFQlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cN6aFQl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cN6aFQl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'location' => ['privates', '.errored..service_locator.cN6aFQl.App\\Entity\\Location', NULL, 'Cannot autowire service ".service_locator.cN6aFQl": it needs an instance of "App\\Entity\\Location" but this type has been excluded in "config/services.yaml".'],
            'repository' => ['privates', '.errored.6guCk.s', NULL, 'Cannot determine controller argument for "App\\Controller\\WeatherController::city()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MeasurementRepository". Did you forget to add a use statement?'],
        ], [
            'location' => 'App\\Entity\\Location',
            'repository' => '?',
        ]);
    }
}
