<?php

namespace ContainerPYTR9HB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_6guCk_SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.6guCk.s' shared service.
     *
     * @return \App\Controller\MeasurementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\WeatherController::city()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MeasurementRepository". Did you forget to add a use statement?');
    }
}
