<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ8eFrSI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ8eFrSI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ8eFrSI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ8eFrSI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ8eFrSI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q8eFrSI',
    'container.build_id' => 'd125d259',
    'container.build_time' => 1701641381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ8eFrSI');
