<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< Updated upstream
if (\class_exists(\ContainerCWkVgqM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCWkVgqM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCWkVgqM.legacy');
=======
if (\class_exists(\ContainerBiSDMjX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBiSDMjX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBiSDMjX.legacy');
>>>>>>> Stashed changes

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< Updated upstream
    \class_alias(\ContainerCWkVgqM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCWkVgqM\App_KernelDevDebugContainer([
    'container.build_hash' => 'CWkVgqM',
    'container.build_id' => 'b7dd2fa6',
    'container.build_time' => 1701021262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCWkVgqM');
=======
    \class_alias(\ContainerBiSDMjX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBiSDMjX\App_KernelDevDebugContainer([
    'container.build_hash' => 'BiSDMjX',
    'container.build_id' => '8cf3a5a8',
    'container.build_time' => 1701021038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBiSDMjX');
>>>>>>> Stashed changes
