<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCWkVgqM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCWkVgqM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCWkVgqM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCWkVgqM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCWkVgqM\App_KernelDevDebugContainer([
    'container.build_hash' => 'CWkVgqM',
    'container.build_id' => 'b7dd2fa6',
    'container.build_time' => 1701021262,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCWkVgqM');
