<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRtwCa1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRtwCa1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCRtwCa1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCRtwCa1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCRtwCa1\App_KernelDevDebugContainer([
    'container.build_hash' => 'CRtwCa1',
    'container.build_id' => '5185aa9f',
    'container.build_time' => 1698488860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRtwCa1');
